"""adjusted user table

Revision ID: 0052f0b5ab13
Revises: 8f98e74132f6
Create Date: 2024-08-02 13:24:17.056879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0052f0b5ab13'
down_revision = '8f98e74132f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone_no', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['email_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_no')
        batch_op.drop_column('email_id')

    # ### end Alembic commands ###
