"""Create pn_raw table

Revision ID: 8f98e74132f6
Revises: a69a68f2fdd4
Create Date: 2024-08-02 12:59:03.598494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f98e74132f6'
down_revision = 'a69a68f2fdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pn_raw',
    sa.Column('unique_id', sa.String(length=100), nullable=False),
    sa.Column('payment_notice_id', sa.String(length=100), nullable=True),
    sa.Column('contractor_afp_ref', sa.String(length=100), nullable=True),
    sa.Column('pn_date_issued_to_contractor', sa.String(length=100), nullable=True),
    sa.Column('date_of_application', sa.String(length=100), nullable=True),
    sa.Column('purchase_order_id', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('exchange_id', sa.String(length=100), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('contractor', sa.String(length=100), nullable=True),
    sa.Column('polygon_type', sa.String(length=100), nullable=True),
    sa.Column('polygon_id', sa.String(length=100), nullable=True),
    sa.Column('feature_id', sa.String(length=100), nullable=True),
    sa.Column('build_status', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('total', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('afp_claim_ok_nok', sa.String(length=100), nullable=True),
    sa.Column('nok_reason_code', sa.String(length=100), nullable=True),
    sa.Column('approved_quantity', sa.String(length=100), nullable=True),
    sa.Column('approved_total', sa.String(length=100), nullable=True),
    sa.Column('concate', sa.String(length=100), nullable=True),
    sa.Column('qgis_quant', sa.String(length=100), nullable=True),
    sa.Column('qgis_rate', sa.String(length=100), nullable=True),
    sa.Column('qgis_url', sa.String(length=255), nullable=True),
    sa.Column('po_check', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pn_raw')
    # ### end Alembic commands ###
