"""Add Taken_To_Revenue_Date column to EODDump

Revision ID: a69a68f2fdd4
Revises: 
Create Date: 2024-08-02 12:44:48.051173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a69a68f2fdd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod_dump', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Taken_To_Revenue_Date', sa.DateTime(), nullable=True))
        batch_op.alter_column('Gang',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eod_dump', schema=None) as batch_op:
        batch_op.alter_column('Gang',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('Taken_To_Revenue_Date')

    # ### end Alembic commands ###
